### ISSUE TITLE
Mention dupliquée si multiples parcours

### ISSUE THREAD

**Issue by florent-n** [Dannebicque/oreof#2]
Dès que l'on crée 2 parcours dans une mention/spé, l'affichage montre 2 fois la même mention.
![Capture d’écran 2023-06-14 143802](https://github.com/Dannebicque/oreof/assets/8950647/40a3ab5a-0d33-4bcd-a41f-5ebd908b6545)

**Comment by Dannebicque** [comment]
Corrigé, merci de nouveau Florent.
